# See this wiki page for more info:
# https://github.com/dylanaraps/neofetch/wiki/Customizing-Info
print_info() {
    info title
    #info underline
    
    info "distro" distro
    info "host" model
    info "kernel" kernel
    info "packages" packages
    info "shell" shell
    info "memory" memory
    info "disk" disk
    #info "CPU" cpu
    #info "CPU usage" cpu_usage
    #info "GPU" gpu
    #info "GPU driver" gpu_driver  # Linux/macOS only
    #info "uptime" uptime
    #info "resolution" resolution
    #info "de" de
    #info "wm" wm
    #info "wm theme" wm_theme
    #info "theme" theme
    #info "icons" icons
    #info "terminal" term
    #info "terminal font" term_font
    #info "battery" battery
    #info "font" font
    #info "local IP" local_ip
    #info "public IP" public_ip
    #info "users" users
    #info "locale" locale  # This only works on glibc systems.
    
    info cols
}

# Distro -> Show/Hide OS Architecture.
# Show 'x86_64', 'x86' and etc in 'Distro:' output.
# Default: 'on'
# Values:  'on', 'off'
os_arch="off"

# Uptime - Shorten the output of the uptime function
# Default: 'on'
# Values:  'on', 'tiny', 'off'
uptime_shorthand="tiny"

# Memory
# Show memory pecentage in output.
# Default: 'off'
# Values:  'on', 'off'
memory_percent="on"
# Change memory output unit.
# Default: 'mib'
# Values:  'kib', 'mib', 'gib'
memory_unit="gib"

# Packages - Show/Hide Package Manager names.
# Default: 'tiny'
# Values:  'on', 'tiny' 'off'
package_managers="on"

# CPU Temperature - Hide/Show CPU temperature.
# Default: 'off'
# Values:  'C', 'F', 'off'
cpu_temp="C"

# Text Options:
# Colors
# Default:  'distro'
# Values:   'distro', 'num' 'num' 'num' 'num' 'num' 'num'
# Each number represents a different part of the text in
# this order: 'title', '@', 'underline', 'subtitle', 'colon', 'info'
colors=(4 6 1 8 8 7)
# Info Separator
# Replace the default separator with the specified string.
# Default:  ':'
separator=' ->'

# Ascii Options
# Distro - Which distro's ascii art to display.
# Default: 'auto'
# Values:  'auto', 'distro_name'
# NOTE: Arch, Ubuntu, Redhat, and Dragonfly have 'old' logo variants.
#       Use '{distro name}_old' to use the old logos.
# NOTE: Arcolinux, Dragonfly, Fedora, Alpine, Arch, Ubuntu,
#       CRUX, Debian, Gentoo, FreeBSD, Mac, NixOS, OpenBSD, android,
#       Antrix, CentOS, Cleanjaro, ElementaryOS, GUIX, Hyperbola,
#       Manjaro, MXLinux, NetBSD, Parabola, POP_OS, PureOS,
#       Slackware, SunOS, LinuxLite, OpenSUSE, Raspbian,
#       postmarketOS, and Void have a smaller logo variant.
#       Use '{distro name}_small' to use the small variants.
ascii_distro="auto"
# Colors
# Default:  'distro'
# Values:   'distro', 'num' 'num' 'num' 'num' 'num' 'num'
ascii_colors=('distro')



