# Set new prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Reload Config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded tmux config!"

# Kill server
bind K kill-server

# Enable mouse support
set -g mouse on

# Window management
# Splitting
unbind h
unbind '"' # horizontal
unbind v
unbind % # vertical
bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
# Creating
unbind w # change window interactively
unbind n # move to next window
bind w new-window -c "#{pane_current_path}"
bind n command-prompt "rename-window '%%'"
# Use 1-based indexing
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
# Changing
bind -n M-j next-window
bind -n M-k previous-window # M => alt

# For Copy mode
# ( launch with '<prefix>[' and leave with 'q' )
# ( paste with '<prefix>]' )
set-window-option -g mode-keys vi
unbind -T copy-mode-vi Space; # begin-selection
unbind -T copy-mode-vi Enter; # copy-selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Put status bar on top
#set-option -g status-position top
# Set true colour
set-option -sa terminal-overrides ",xterm*:Tc"

### Plugin management
# <prefix>I - install | <prefix>U - update
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
# Rosé Pine theme
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'
#set -g @rose_pine_only_windows 'on'
set -g @rose_pine_window_status_separator "  "

run '~/.tmux/plugins/tpm/tpm'

